repos:
  # Pre-commit hooks for basic file checks and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast              # Verify if files can be parsed as valid Python AST
      - id: check-case-conflict    # Detect conflicting file names with different casing
      - id: check-docstring-first  # Ensure docstrings are at the beginning of modules, functions, or classes
      - id: check-json             # Validate that JSON files are properly formatted
        exclude: .vscode           # Exclude the .vscode directory
      - id: check-symlinks         # Ensure that symlinks are valid
      - id: check-toml             # Validate the structure of TOML files
      - id: check-vcs-permalinks   # Ensure version control URLs use permalinks
      - id: check-yaml             # Validate the structure of YAML files
      - id: detect-private-key     # Detect accidentally committed private keys
      - id: end-of-file-fixer      # Ensure files end with a newline
      - id: mixed-line-ending      # Fix mixed line endings (e.g., CRLF and LF)
        args: [--fix=lf]           # Convert line endings to LF
      - id: pretty-format-json     # Automatically format JSON files
        args: [--autofix]          # Fix formatting issues automatically
      - id: requirements-txt-fixer # Sort and deduplicate `requirements.txt` entries
      - id: trailing-whitespace    # Remove trailing whitespace from files

  # Ruff: Linter and formatter for Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff                          # Perform linting on Python code
        types_or: [python, pyi, jupyter]  # Apply to Python, .pyi, and Jupyter files
        args: [--fix]                     # Automatically fix linting issues where possible
      - id: ruff-format                   # Format Python code with Ruff
        types_or: [python, pyi, jupyter]  # Apply to Python, .pyi, and Jupyter files

  # Bandit: Security analysis for Python code
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit   # Identify potential security issues in Python code
