name: 'CI/CD'

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
      - name: Create credentials file
        run: echo "${{ secrets.SA_TERRAFORM_KEY }}" > sa-terraform.json
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Format
        run: terraform -chdir=terraform fmt -check
      - name: Terraform Plan
        run: terraform -chdir=terraform plan \
                -input=false \
                -no-color \
                -out=tfplan.txt \
                -var="credentials_file=sa-terraform.json" \
                -var="project_id=${{ vars.PROJECT_ID }}" \
                -var="region=${{ vars.REGION }}"
      - name: Show Terraform Plan
        run: terraform -chdir=terraform show tfplan.txt

  terraform-apply:
    if: github.ref == 'refs/heads/main'
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: cloud
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
      - name: Create credentials file
        run: echo "${{ secrets.SA_TERRAFORM_KEY }}" > sa-terraform.json
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve \
                -input=false \
                -var="credentials_file=sa-terraform.json" \
                -var="project_id=${{ vars.PROJECT_ID }}" \
                -var="region=${{ vars.REGION }}"
